import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Todos from "./components/Todos";
import CreateTodo from "./components/CreateTodo";
export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Full stack App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-5xl font-extrabold text-white">
          Todos
        </h1>
        {sessionData && (
          <div className="flex flex-col items-center justify-center gap-4 bg-white/10 p-10 rounded-md h-auto w-96 mt-3">
          <Todos />
          <CreateTodo/>
          </div>
        )}

        <div className="flex flex-col items-center justify-center gap-4">
          <p className="text-center text-2xl text-white">
            {sessionData && <span>Logged in as {sessionData.user?.email}</span>}{" "}
          </p>

          <button
            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
            onClick={sessionData ? () => void signOut() : () => void signIn()}
          >
            {sessionData ? "Sign out" : "Sign in"}
          </button>
          
        </div>


      </main>
    </>
  );
}

